/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import modeloqytetet.*;
import java.util.ArrayList;
//import InterfazTextualQytetet.VistaTextualQytetet;

/**
 *
 * @author fran
 */
import javax.swing.JOptionPane;

public class ControladorQytetet extends javax.swing.JFrame {

    Qytetet modeloQytetet;

    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        initComponents();
    }

    public void habilitarComenzarTurno() {
        this.jbComprar.setEnabled(false);
        this.jbPasaTurno.setEnabled(false);
        this.jbAplicarSorpresa.setEnabled(false);
        if (modeloQytetet.getJugadorActual().isEncarcelado()) {
            this.jbCarcelPagando.setEnabled(true);
            this.jbCarcelDado.setEnabled(true);
        } else {
            this.jbJugar.setEnabled(true);
            this.jbCarcelPagando.setEnabled(false);
            this.jbCarcelDado.setEnabled(false);
        }
    }

    public void actualizar(Qytetet juego) {
        habilitarComenzarTurno();
        vistaQytetet.actualizar(juego);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbCarcelDado = new javax.swing.JButton();
        jbComprar = new javax.swing.JButton();
        jbCarcelPagando = new javax.swing.JButton();
        jbJugar = new javax.swing.JButton();
        jbAplicarSorpresa = new javax.swing.JButton();
        jbPasaTurno = new javax.swing.JButton();
        vistaQytetet = new GUIQytetet.VistaQytetet();
        jbGestionInmobiliaria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbCarcelDado.setText("Salir Carcel Dado");

        jbComprar.setText("Comprar");

        jbCarcelPagando.setText("Salir Carcel Pagando");
        jbCarcelPagando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarcelPagandoActionPerformed(evt);
            }
        });

        jbJugar.setText("Jugar");
        jbJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJugarActionPerformed(evt);
            }
        });

        jbAplicarSorpresa.setText("Aplicar Sorpresa");
        jbAplicarSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAplicarSorpresaActionPerformed(evt);
            }
        });

        jbPasaTurno.setText("Pasa Turno");
        jbPasaTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPasaTurnoActionPerformed(evt);
            }
        });

        jbGestionInmobiliaria.setText("Gestion Inmobiliaria");
        jbGestionInmobiliaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionInmobiliariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCarcelPagando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCarcelDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbGestionInmobiliaria)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAplicarSorpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPasaTurno)
                    .addComponent(jbComprar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(vistaQytetet, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbAplicarSorpresa, jbComprar, jbPasaTurno});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaQytetet, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAplicarSorpresa)
                        .addGap(2, 2, 2)
                        .addComponent(jbPasaTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbComprar)
                            .addComponent(jbGestionInmobiliaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCarcelDado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbCarcelPagando))
                            .addComponent(jbJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbGestionInmobiliaria.getAccessibleContext().setAccessibleName("jbGestionInmobiliaria");
        jbGestionInmobiliaria.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPasaTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPasaTurnoActionPerformed
        modeloQytetet.siguienteJugador();
        this.actualizar(modeloQytetet);
    }//GEN-LAST:event_jbPasaTurnoActionPerformed

    private void jbCarcelPagandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarcelPagandoActionPerformed
        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.PAGANDOLIBERTAD);
        this.jbCarcelPagando.setEnabled(false);
        this.jbCarcelDado.setEnabled(false);
        if (resultado) {
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.jbJugar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "NO sales de la carcel");
            this.jbPasaTurno.setEnabled(true);
        }
        this.actualizar(modeloQytetet);
    }//GEN-LAST:event_jbCarcelPagandoActionPerformed

    private void jbJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJugarActionPerformed
        boolean tienePropietario = modeloQytetet.jugar();

    }//GEN-LAST:event_jbJugarActionPerformed

    private void jbAplicarSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAplicarSorpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAplicarSorpresaActionPerformed

    private void jbGestionInmobiliariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionInmobiliariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGestionInmobiliariaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ControladorQytetet controladorQytetet = new ControladorQytetet();

        CapturaNombreJugadores capturaNombres
                = new CapturaNombreJugadores(controladorQytetet, true);
        ArrayList<String> nombres = capturaNombres.obtenerNombres();
        controladorQytetet.modeloQytetet = Qytetet.getInstance();
        controladorQytetet.modeloQytetet.inicicializarJuego(nombres);
        controladorQytetet.actualizar(Qytetet.getInstance());
        Dado.createInstance(controladorQytetet);

        controladorQytetet.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAplicarSorpresa;
    private javax.swing.JButton jbCarcelDado;
    private javax.swing.JButton jbCarcelPagando;
    private javax.swing.JButton jbComprar;
    private javax.swing.JButton jbGestionInmobiliaria;
    private javax.swing.JButton jbJugar;
    private javax.swing.JButton jbPasaTurno;
    private GUIQytetet.VistaQytetet vistaQytetet;
    // End of variables declaration//GEN-END:variables
}
